version: 0.2

phases:
  install:
    commands:
      # - command
      # - command
        - npm install

  build:
    commands:
     - npm run build && aws s3 sync build/ s3://bucket-full(https://ec2-samplebucket.s3.ap-south-1.amazonaws.com/photo.jpg) 
